---
- name: Configures mesh worker nodes - {{ track_slug }}
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Include variable tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/60_check_vars.yml"

  tasks:
    - name: Include common user tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/5_configure_users.yml"

    - name: Include common mesh worker node tasks
      vars:
        instance_os_packages:
          - receptor
          - receptorctl
          - podman
          - crun
          - ansible-runner
          - subscription-manager-rhsm-certificates
          - rsync
          - git
          - ansible-core
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/30_mesh_node.yml"

    - name: Include common image cleanup tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/10_image_cleanup.yml"
