---
- name: Configure base RHEL image
  hosts: all
  gather_facts: true
  become: true
  vars:
    admin_password: 'ansible123!'
    student_username: "student"
    student_password: "learn_ansible"
    aap_dir: "/home/{{ ansible_user }}/aap_install"
  tasks:
    - name: Include user setup tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/5_configure_users.yml"
        apply:
          tags:
            - user-setup
      tags:
        - user-setup

    - name: Include common image cleanup tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/10_image_cleanup.yml"
        apply:
          tags:
            - image-cleanup
      tags:
        - image-cleanup

    - name: Install OS packages
      ansible.builtin.dnf:
        name:
          - podman
          - wget
        state: present
